# Route for generating images
#responsive_image:
#    path:     /%responsive_image.image_directory%/%responsive_image.image_styles_directory%/{stylename}/{filename}
#    defaults: { _controller: ResponsiveImageBundle:Image:index }