custom_image_settings:
    path:     /admin/image_settings
    defaults: { _controller: ResponsiveImageBundle:Styles:index }

custom_image:
    path:     /%image_directory%/%image_styles_directory%/{stylename}/{filename}
    defaults: { _controller: ResponsiveImageBundle:Image:index }