#
# This is the default configuration for this bundle.
#
services:
    responsive_image:
        class: IrishDan\ResponsiveImageBundle\ResponsiveImageManager
        arguments:
            - '@responsive_image.style_manager'
            - '%responsive_image%'
            - '@responsive_image.uploader'

    responsive_image.image_manager:
        class: IrishDan\ResponsiveImageBundle\ImageProcessing\ImageManager
        arguments:
            - '@responsive_image.style_manager'
            - '@responsive_image.image_styler'
            - '@responsive_image.file_system_factory'
            - '@responsive_image_temp'
            - '@event_dispatcher'

    responsive_image.style_manager:
        class: IrishDan\ResponsiveImageBundle\StyleManager
        arguments: [ '%responsive_image%' ]

    responsive_image.image_styler:
        class: IrishDan\ResponsiveImageBundle\ImageProcessing\ImageStyler
        arguments: [ '%responsive_image%' ]

    responsive_image.file_to_object:
        class: IrishDan\ResponsiveImageBundle\File\FileToObject
        arguments: [ '@doctrine.orm.entity_manager', '%responsive_image.entity_class%' ]

    # Responsive image locator
    responsive_image.image_class_locator:
        class: IrishDan\ResponsiveImageBundle\ImageEntityClassLocator
        arguments: ['%kernel.bundles%','@file_locator']

    # Command
    responsive_image.command.generate_entity:
            class: IrishDan\ResponsiveImageBundle\Command\GenerateImageEntityCommand
            arguments: [ '%responsive_image.entity_class%' ]
            tags:
                - { name: console.command }

    responsive_image.command.generate_crud:
        class: IrishDan\ResponsiveImageBundle\Command\GenerateImageEntityCrudCommand
        # parent: Sensio\Bundle\GeneratorBundle\Command\GenerateDoctrineCrudCommand
        tags:
            - { name: console.command }

    # filesystem
    responsive_image.file_system_factory:
        class: IrishDan\ResponsiveImageBundle\FileSystem\PrimaryFileSystemWrapper
        arguments: [ '@event_dispatcher', '@responsive_image_filesystem' ]

    # Uploader
    responsive_image.uploader:
        class: IrishDan\ResponsiveImageBundle\Uploader
        arguments:
            - '@responsive_image.file_system_factory'
            - '@responsive_image.filename_transliterator'
            - '@responsive_image.file_validator'

    responsive_image.filename_transliterator:
        class: IrishDan\ResponsiveImageBundle\File\FilenameTransliterator
        arguments: ['@responsive_image.file_to_object']

    responsive_image.file_validator:
        class: IrishDan\ResponsiveImageBundle\File\FileValidator

    # URL builder
    responsive_image.url_builder:
        class: IrishDan\ResponsiveImageBundle\Url\UrlBuilder
        arguments: ['@responsive_image.file_system_factory', '%responsive_image%']
        calls:
            - [ setAdapterUrlEncoder, [ 'Local' , '@responsive_image.local_url']]
            - [ setAdapterUrlEncoder, [ 'AwsS3Adapter' , '@responsive_image.aws_url']]

    responsive_image.local_url:
        class: IrishDan\ResponsiveImageBundle\Url\LocalAdapterUrlEncoder
        shared: false

    responsive_image.aws_url:
        class: IrishDan\ResponsiveImageBundle\Url\AwsAdapterUrlEncoder
        shared: false

    # Custom form field type.
    responsive_image.form.type.crop_focus:
        class: IrishDan\ResponsiveImageBundle\Form\CropFocusType
        arguments: [ '@responsive_image.style_manager', '%responsive_image%' ]
        tags:
            - { name: form.type }

    responsive_image.form.type.responsive_image:
        class: IrishDan\ResponsiveImageBundle\Form\ResponsiveImageType
        arguments: [ '%responsive_image.entity_class%' ]
        tags:
            - { name: form.type }

    # Event subscribers
    responsive_image.image_event_subscriber:
        class: IrishDan\ResponsiveImageBundle\EventSubscriber\ImageSubscriber
        arguments: [ '@responsive_image.image_manager','@logger' ]
        tags:
            - { name: kernel.event_subscriber }

    responsive_image.uploader_event_subscriber:
        class: IrishDan\ResponsiveImageBundle\EventSubscriber\UploaderSubscriber
        arguments: [ '@logger', '@responsive_image_filesystem' ]
        tags:
            - { name: kernel.event_subscriber }

    responsive_image.file_system_event_subscriber:
        class: IrishDan\ResponsiveImageBundle\EventSubscriber\FileSystemSubscriber
        arguments: [ '@logger' ]
        tags:
            - { name: kernel.event_subscriber }

    responsive_image.styled_image_event_subscriber:
        class: IrishDan\ResponsiveImageBundle\EventSubscriber\StyledImagesSubscriber
        arguments:
            - '@responsive_image.file_system_factory'
            - '@responsive_image_temp'
            - '@logger'
        tags:
            - { name: kernel.event_subscriber }

    # Twig extensions
    responsive_image.twig_extension:
        class: IrishDan\ResponsiveImageBundle\Twig\ResponsiveImageExtension
        public: false
        arguments: [ '@responsive_image.style_manager', '@responsive_image.url_builder' , '@responsive_image.image_manager']
        tags:
            - { name: twig.extension }