services:
    responsive_image:
        class: IrishDan\ResponsiveImageBundle\ResponsiveImageManager
        arguments:
            - '@responsive_image.style_manager'
            - '%responsive_image%'
            - '@responsive_image.uploader'

    responsive_image.image_manager:
        class: IrishDan\ResponsiveImageBundle\Image\ImageManager
        arguments:
            - '@responsive_image.style_manager'
            - '@responsive_image.image_maker'
            - '@response_image.file_system_factory'
            - '@responsive_image_temp'
            - '@event_dispatcher'

    responsive_image.style_manager:
        class: IrishDan\ResponsiveImageBundle\StyleManager
        arguments: [ '%responsive_image%' ]

    responsive_image.image_maker:
        class: IrishDan\ResponsiveImageBundle\ImageMaker
        arguments: [ '%responsive_image%' ]

    responsive_image.file_to_object:
        class: IrishDan\ResponsiveImageBundle\FileToObject
        arguments: [ '@doctrine.orm.entity_manager', '%responsive_image.entity_class%' ]

    # filesystem
    response_image.file_system_factory:
        class: IrishDan\ResponsiveImageBundle\FileSystem\FileSystemFactory
        arguments: [ '@event_dispatcher', '@responsive_image_filesystem' ]

    # Uploader
    responsive_image.uploader:
        class: IrishDan\ResponsiveImageBundle\Uploader
        arguments:
            - '@response_image.file_system_factory'
            - '@responsive_image.filename_transliterator'
            - '@responsive_image.file_validator'
        #calls:
        #    - [ setFileSystem, [ '@responsive_image_filesystem' ]]

    responsive_image.filename_transliterator:
        class: IrishDan\ResponsiveImageBundle\File\FilenameTransliterator
        arguments: ['@responsive_image.file_to_object']

    responsive_image.file_validator:
        class: IrishDan\ResponsiveImageBundle\File\FileValidator

    # url builder
    responsive_image.url_builder:
        class: IrishDan\ResponsiveImageBundle\UrlBuilder
        arguments: ['@response_image.file_system_factory']

    # Custom form field type.
    responsive_image.form.type.crop_focus:
        class: IrishDan\ResponsiveImageBundle\Form\CropFocusType
        arguments: [ '@responsive_image.style_manager', '%responsive_image%' ]
        tags:
            - { name: form.type }

    responsive_image.form.type.responsive_image:
        class: IrishDan\ResponsiveImageBundle\Form\ResponsiveImageType
        arguments: [ '%responsive_image.entity_class%' ]
        tags:
            - { name: form.type }

    # Event subscribers
    responsive_image.uploader_event_subscriber:
        class: IrishDan\ResponsiveImageBundle\EventListener\UploaderSubscriber
        arguments: [ '@logger', '@responsive_image_filesystem' ]
        tags:
            - { name: kernel.event_subscriber }

    responsive_image.file_system_event_subscriber:
        class: IrishDan\ResponsiveImageBundle\EventListener\FileSystemSubscriber
        arguments: [ '@logger' ]
        tags:
            - { name: kernel.event_subscriber }

    responsive_image.styled_image_event_subscriber:
        class: IrishDan\ResponsiveImageBundle\EventListener\StyledImagesSubscriber
        arguments:
            - '@logger'
            - '@response_image.file_system_factory'
            - '@responsive_image_temp'
        tags:
            - { name: kernel.event_subscriber }

    # Event listeners.
    # responsive_image.listener.image_generate_styled:
    #     class: IrishDan\ResponsiveImageBundle\EventListener\ImageListener
    #     arguments: [ '%responsive_image', '@responsive_image' ]
    #     tags:
    #         - { name: kernel.event_listener, event: responsive_image.image_generate_styled, method: imageGenerateStyled }

    # responsive_image.listener.image_delete_all:
    #     class: IrishDan\ResponsiveImageBundle\EventListener\ImageListener
    #     arguments: [ '%responsive_image', '@responsive_image' ]
    #     tags:
    #         - { name: kernel.event_listener, event: responsive_image.image_delete_all, method: imageDeleteAll }

    # responsive_image.listener.image_delete_styled:
    #     class: IrishDan\ResponsiveImageBundle\EventListener\ImageListener
    #     arguments: [ '%responsive_image', '@responsive_image' ]
    #     tags:

    # responsive_image.listener.style_delete_styled:
    #     class: IrishDan\ResponsiveImageBundle\EventListener\ImageListener
    #     arguments: [ '%responsive_image', '@responsive_image' ]
    #     tags:
    #         - { name: kernel.event_listener, event: responsive_image.style_delete_styled, method: styleDeleteStyled }

    # responsive_image.listener.style_delete_all:
    #     class: IrishDan\ResponsiveImageBundle\EventListener\ImageListener
    #     arguments: [ '%responsive_image', '@responsive_image' ]
    #     tags:
    #         - { name: kernel.event_listener, event: responsive_image.style_delete_all, method: styleDeleteAll }

    # Twig extensions
    responsive_image.twig_extension:
        class: IrishDan\ResponsiveImageBundle\Twig\ResponsiveImageExtension
        public: false
        arguments: [ '@responsive_image.style_manager', '@responsive_image.url_builder' ]
        tags:
            - { name: twig.extension }