services:
  responsive_image:
      class: ResponsiveImageBundle\Utils\ResponsiveImageManager
      arguments: [ '@responsive_image.image_maker', '@responsive_image.style_manager', '%responsive_image%', '@responsive_image.file_system', '@responsive_image.s3_bridge', '@responsive_image.uploader' ]

  responsive_image.file_system:
      class: ResponsiveImageBundle\Utils\FileSystem
      arguments: ['%kernel.root_dir%', '%responsive_image%' ]

  responsive_image.style_manager:
      class: ResponsiveImageBundle\Utils\StyleManager
      arguments: ['@responsive_image.file_system', '%responsive_image%' ]

  responsive_image.image_maker:
      class: ResponsiveImageBundle\Utils\ImageMaker
      arguments: [ '@responsive_image.file_system', '%responsive_image%' ]

  responsive_image.file_to_object:
      class: ResponsiveImageBundle\Utils\FileToObject
      arguments: [ '@doctrine.orm.entity_manager' ]

  responsive_image.uploader:
      class: ResponsiveImageBundle\Utils\Uploader
      arguments: ['@responsive_image.file_system']

  responsive_image.s3_bridge:
      class: ResponsiveImageBundle\Utils\S3Bridge
      arguments: [ '%responsive_image.aws_s3%' ]

  # Custom form field type.
  responsive_image.form.type.crop_focus:
      class: ResponsiveImageBundle\Form\Type\CropFocusType
      arguments: [ '@responsive_image.style_manager', '%responsive_image%' ]
      tags:
          - { name: form.type }

  # Form handlers.
  responsive_image.styles_form_handler:
      class: ResponsiveImageBundle\Form\Handler\StylesFormHandler
      arguments: [ '@responsive_image.style_manager', '@event_dispatcher' ]

  # Event listeners.
  responsive_image.listener.image_generate_styled:
      class: ResponsiveImageBundle\Event\ImageListener
      arguments: [ '%responsive_image', '@responsive_image' ]
      tags:
          - { name: kernel.event_listener, event: responsive_image.image_generate_styled, method: imageGenerateStyled }

  responsive_image.listener.image_delete_all:
      class: ResponsiveImageBundle\Event\ImageListener
      arguments: [ '%responsive_image', '@responsive_image' ]
      tags:
          - { name: kernel.event_listener, event: responsive_image.image_delete_all, method: imageDeleteAll }

  responsive_image.listener.image_delete_styled:
      class: ResponsiveImageBundle\Event\ImageListener
      arguments: [ '%responsive_image', '@responsive_image' ]
      tags:
          - { name: kernel.event_listener, event: responsive_image.image_delete_styled, method: imageDeleteStyled }

  responsive_image.listener.style_delete_styled:
      class: ResponsiveImageBundle\Event\ImageListener
      arguments: [ '%responsive_image', '@responsive_image' ]
      tags:
          - { name: kernel.event_listener, event: responsive_image.style_delete_styled, method: styleDeleteStyled }

  responsive_image.listener.style_delete_all:
      class: ResponsiveImageBundle\Event\ImageListener
      arguments: [ '%responsive_image', '@responsive_image' ]
      tags:
          - { name: kernel.event_listener, event: responsive_image.style_delete_all, method: styleDeleteAll }