services:
  responsive_image.file_system:
      class: ResponsiveImageBundle\Utils\FileSystem
      arguments: ['%kernel.root_dir%', '%responsive_image%' ]

  responsive_image.style_manager:
      class: ResponsiveImageBundle\Utils\StyleManager
      arguments: ['@responsive_image.file_system', '%responsive_image%' ]

  responsive_image.imager:
      class: ResponsiveImageBundle\Utils\Imager
      arguments: [ '@responsive_image.file_system', '%responsive_image%' ]

  responsive_image.file_to_object:
      class: ResponsiveImageBundle\Utils\FileToObject
      arguments: [ '@doctrine.orm.entity_manager' ]

  responsive_image.uploader:
      class: ResponsiveImageBundle\Utils\Uploader
      arguments: ['@responsive_image.file_system']

  # Custom form field type.
  responsive_image.form.type.gender:
      class: ResponsiveImageBundle\Form\Type\CropFocusType
      arguments: [ '@responsive_image.style_manager', '%responsive_image%' ]
      tags:
          - { name: form.type }

  # Form handlers.
  responsive_image.styles_form_handler:
      class: ResponsiveImageBundle\Form\Handler\StylesFormHandler
      arguments: [ '@responsive_image.style_manager' ]